- project:
    check:
      jobs:
        - "thoth-coala"
    gate:
      queue: "qeb-hwt"
      jobs:
        - "thoth-coala"
    kebechet-auto-gate:
      queue: "qeb-hwt"
      jobs:
        - "thoth-coala"
