apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: qeb-hwt
    component: github-app
  name: qeb-hwt-github-app
spec:
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: qeb-hwt-github-app:latest
  source:
    git:
      ref: master
      uri: https://github.com/thoth-station/Qeb-Hwt.git
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: ENABLE_PIPENV
          value: "1"
        - name: THOTH_ADVISE
          value: "0"
        - name: THOTH_DRY_RUN
          value: "1"
      from:
        kind: ImageStreamTag
        name: s2i-thoth-fedora30-py37:latest
    type: Source
  triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
    - github:
        secret: 0150d044a6b6dc24
      type: GitHub
