apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: qeb-hwt
  labels:
    app: qeb-hwt
    component: github-app
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    app: qeb-hwt
    component: github-app
  template:
    metadata:
      labels:
        app: qeb-hwt
        component: github-app
    spec:
      containers:
        - env:
            - name: ENV
              value: prod
            - name: PYTHONPATH
              value: .
            - name: THOTH_DEPLOYMENT_NAME
              value: aicoe-openshift_com-prod
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: sentry-dsn
                  name: qeb-hwt-github-app
          envFrom:
            - prefix: GITHUB_
              secretRef:
                name: qeb-hwt-github-app
          image: qeb-hwt-github-app:latest
          name: github-app
          ports:
            - containerPort: 8080
              protocol: TCP
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - github-app
        from:
          kind: ImageStreamTag
          name: qeb-hwt-github-app:latest
      type: ImageChange
    - type: ConfigChange
