---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: qeb-hwt
    component: github-app
  name: qeb-hwt-github-app
spec:
  lookupPolicy:
    local: True
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-thoth-fedora30-py37
spec:
  lookupPolicy:
    local: True
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/thoth-station/s2i-thoth-fedora30-py37:v0.5.0
      importPolicy: {}
      referencePolicy:
        type: Source
