apiVersion: v1
kind: Service
metadata:
  labels:
    app: qeb-hwt
    component: github-app
  name: qeb-hwt-github-app
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: qeb-hwt
    component: github-app
  type: ClusterIP
